In [30]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import sklearn


from sklearn.feature_extraction.text import TfidfVectorizer


from sklearn.model_selection import train_test_split

from sklearn import metrics

In [1]:
#Read both the datas 

In [2]:
df1 = pd.read_csv(r"C:\Users\navin\Downloads\twitter-and-reddit-sentimental-analysis-dataset\Reddit_Data.csv")
df2 = pd.read_csv(r"C:\Users\navin\Downloads\twitter-and-reddit-sentimental-analysis-dataset\Twitter_Data.csv")

In [3]:
df1.head()

clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
3  what you have learned yours and only yours wha...         0
4  for your own benefit you may want read living ...         1

In [4]:
df2.head()

clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [2]:
#Check NaN values in df1 and drop them

In [5]:
df1.isnull().sum()

clean_comment    100
category           0
dtype: int64

In [7]:
df1 = df1.dropna(axis = 0)

In [3]:
#Check NaN values in df2 and drop them

In [9]:
df2.isnull().sum()

clean_text    4
category      7
dtype: int64

In [10]:
df2 = df2.dropna(axis = 0)

In [4]:
#Checking data type of "Category" in df2

In [11]:
df2["category"].dtype

dtype('float64')

In [5]:
#Converting it to int

In [12]:
df2["category"] = df2["category"].astype(int)

In [6]:
#Renaming "clean_comment" in df1 to "clean_text"

In [13]:
df1.rename(columns = {'clean_comment':'clean_text'}, inplace = True) 

In [7]:
#Concatinating df1 and df2

In [14]:
dataframe=pd.concat([df1,df2])

In [15]:
dataframe.head()

clean_text  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
3  what you have learned yours and only yours wha...         0
4  for your own benefit you may want read living ...         1

In [16]:
dataframe.tail()

clean_text  category
162975  why these 456 crores paid neerav modi not reco...        -1
162976  dear rss terrorist payal gawar what about modi...        -1
162977  did you cover her interaction forum where she ...         0
162978  there big project came into india modi dream p...         0
162979  have you ever listen about like gurukul where ...         1

In [8]:
#Shuffling the data

In [17]:
dataframe = sklearn.utils.shuffle(dataframe)

In [9]:
#Features

In [18]:
X = dataframe["clean_text"]

In [19]:
X.head()

150345    indian journalists are being bullied toe modi ...
133792    soon modi will join the vast list unemployed p...
83898     modis surgical strikes pakistan non stop multi...
111407                  hahaha cheap modi what rubbish tkng
141132    will dangerous for country prime minister nare...
Name: clean_text, dtype: object

In [10]:
#Labels

In [20]:
y = dataframe["category"]

In [21]:
y.head()

150345    0
133792    0
83898    -1
111407    1
141132   -1
Name: category, dtype: int64

In [11]:
#Converting text to vector form  using TfidVectorizer

In [24]:
tfid_model = TfidfVectorizer()

In [25]:
X = tfid_model.fit_transform(X)

In [27]:
print(X[:1])

  (0, 69433)	0.33004498263779963
  (0, 50061)	0.35133976815683643
  (0, 76447)	0.06791679562422717
  (0, 118934)	0.4861412286398933
  (0, 21831)	0.5307012480577139
  (0, 17085)	0.24003053790622272
  (0, 12107)	0.1462335424172004
  (0, 63149)	0.3474598773504268
  (0, 57828)	0.21286991878122252


In [12]:
#Splitting train test data

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

**MULTINOMIAL NAIVE BAYES**

In [31]:
from sklearn.naive_bayes import MultinomialNB

In [32]:
MultinomialNB_model = MultinomialNB()

In [33]:
MultinomialNB_model.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [35]:
y_pred = MultinomialNB_model.predict(X_test)

In [37]:
acc=metrics.accuracy_score(y_test,y_pred)

In [38]:
print('acuuracy =',acc*100)

acuuracy = 56.47111732960224


In [40]:
Y = tfid_model.transform(["Modi is the best prime Minister"])
MultinomialNB_model.predict(Y)

array([1], dtype=int64)

**BERNOULLI NAIVE BAYES**

In [41]:
from sklearn.naive_bayes import BernoulliNB

In [42]:
BernoulliNB_model = BernoulliNB()

In [43]:
BernoulliNB_model.fit(X_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [44]:
y_pred = BernoulliNB_model.predict(X_test)

In [45]:
acc = metrics.accuracy_score(y_test,y_pred)

In [46]:
print('accuracy =',acc*100)

accuracy = 71.10733559864082


In [48]:
Y = tfid_model.transform(["Modi is not a good prime minister and should be removed"])
BernoulliNB_model.predict(Y)

array([0], dtype=int64)

**LOGISTIC REGRESSION**

In [49]:
from sklearn.linear_model import LogisticRegression

In [50]:
logistic_model=LogisticRegression(random_state=0, solver='lbfgs' ,multi_class='multinomial').fit(X_train,y_train)

c:\users\navin\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [51]:
y_pred=logistic_model.predict(X_test)

In [52]:
acc=metrics.accuracy_score(y_test,y_pred)

In [61]:
print('acuuracy =',acc*100)

acuuracy = 84.66420147911253


In [54]:
Y = tfid_model.transform(["This counry is fucking finished"])
logistic_model.predict(Y)

array([-1], dtype=int64)

**SGD CLASSIFIER**

In [55]:
from sklearn.linear_model import SGDClassifier

In [56]:
sgd_model = SGDClassifier(max_iter=1000 ,random_state=125)

In [57]:
sgd_model.fit(X_train ,y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=125, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [58]:
y_pred=sgd_model.predict(X_test)

In [59]:
acc=metrics.accuracy_score(y_test,y_pred)

In [60]:
print('acuuracy =',acc*100)

acuuracy = 84.66420147911253


In [63]:
Y = tfid_model.transform(["I am neutral about this situation"])
sgd_model.predict(Y)

array([0], dtype=int64)

**SVC**

In [64]:
from sklearn.svm import SVC

In [65]:
svc_model = SVC(max_iter=100,random_state=0,decision_function_shape='ovo',cache_size=500)

In [66]:
svc_model.fit(X_train,y_train)

c:\users\navin\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\_base.py:231: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVC(C=1.0, break_ties=False, cache_size=500, class_weight=None, coef0=0.0,
    decision_function_shape='ovo', degree=3, gamma='scale', kernel='rbf',
    max_iter=100, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [67]:
y_pred=svc_model.predict(X_test)

In [68]:
acc=metrics.accuracy_score(y_test,y_pred) 

In [69]:
print('acuuracy =',acc*100)

acuuracy = 56.22876274235459


In [70]:
Y = tfid_model.transform(["Modi is not the right man"])
svc_model.predict(Y)

array([1], dtype=int64)

**LINEAR SVC**

In [71]:
from sklearn.svm import LinearSVC

In [72]:
linear_svc_model = LinearSVC()

In [73]:
linear_svc_model.fit(X_train,y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [74]:
y_pred=linear_svc_model.predict(X_test)

In [75]:
acc=metrics.accuracy_score(y_test,y_pred)

In [76]:
print('acuuracy =',acc*100)

acuuracy = 94.5532680391765


In [85]:
Y = tfid_model.transform(["are you talking about that program where you allow only those persons speak who can praise you sorry modi kaka not interested"])
linear_svc_model.predict(Y)

array([-1], dtype=int64)

**RANDOM FOREST**

In [79]:
from sklearn.ensemble import RandomForestClassifier

In [80]:
random_forest_model=RandomForestClassifier(n_estimators=1, max_depth=3, random_state=0)

In [81]:
random_forest_model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=3, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [82]:
y_pred=random_forest_model.predict(X_test)

In [83]:
acc=metrics.accuracy_score(y_test,y_pred) 

In [84]:
print('acuuracy =',acc*100)

acuuracy = 44.15850489706176
